# Quick Start Guide

## Connect to Large Scale Storage 
1. If you are an undergraduate student, use your CSAFE email net-id and password in the following steps. 
1. If you are off campus, download the ISU virtual private from https://vpn.iastate.edu and log-in using your ISU net-id and password.
1. On **Windows** open File Explorer and in the top textbox type
    - `\\las.iastate.edu\research` if you are **on campus** or
    - `\\las-dfs-01.las.iastate.edu\lss` if you are **off campus**. 
1. On **Mac** click Go > Connect to Server and type
    - `smb://iastate/lss/research` if you are **on campus** or
    - `smb://las-dfs-01.las.iastate.edu` if you are **off campus**.
1. Enter your net-id and password.
1. Open the research folder and go to your CSAFE project folder.

## Connect to CSAFE Rstudio Server
1. If you are an undergraduate student, use your CSAFE email net-id and password in the following steps. 
1. If you are off campus, download the ISU virtual private from https://vpn.iastate.edu and log-in using your ISU net-id and password.
1. Go to the website https://reiss.csafe.iastate.edu/ or https://locard.csafe.iastate.edu/.
1. Enter your net-id and password.

## Connect to the Pronto Job Scheduler
1. If you are an undergraduate student, use your CSAFE email net-id and password in the following steps. 
1. If you are off campus, download the ISU virtual private from https://vpn.iastate.edu and log-in using your ISU net-id and password.
1. On **Windows** open the PowerShell. On **Mac** open the Terminal.
1. Type `ssh your-netid@pronto.las.iastate.edu`
1. Enter your net-id and password.




